apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: shinian1031/my-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"   # Request at least 64 MiB of memory
            cpu: "250m"       # Request at least 250 millicpu (0.25 CPU core)
          limits:
            memory: "128Mi"  # Allow up to 128 MiB of memory
            cpu: "500m"       # Allow up to 500 millicpu (0.5 CPU core)
